language: c
compiler:
  - gcc
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison git gperf
before_script:
  - rake test
script: 
  - rake test
notifications:
  irc:
    channels:
      - "irc.freenode.org#backdoor-log"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
        - "[%{message}] %{repository} (%{commit}) by %{author}: See %{build_url}"
  webhooks:
    - secure: "kSMxuWQoz7Z5uXUzJwHlATzuWpFBLLfN65LbjLBcTTPQEQ7iRCPlXV+/WkUsz+6kmzKFVNFjmL8lZ/1oC5X3Xs4g/OgmlwiBqkPmGUer0iGsSFfkFb3kSH1XAfmVbzHuSg47H+9sxCaPEIL2h4fBmG0AayXoNjPyTsCgty62gmY="
