language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison git
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cp -fp ../mruby-vedis/build_config.rb .
script: 
  - rake all test
notifications:
  irc:
    channels:
      - "irc.freenode.org#mod_mruby"
    on_success: always
    on_failure: always
    template:
      - "%{message} by @%{author}: See %{build_url}"
